jobs:
  include:
    - os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - os: linux
      dist: xenial
      language: python
      python: 3.7
      before_install:
        - sudo apt-get install python3-tk
        - python --version
        - python -m pip install --upgrade pip

script:
  - pip install -r requirements.txt
  - pytest
  - python package.py

deploy:
  provider: releases
  token: $GITHUB_API_KEY
  file_glob: true
  file: 'artifacts/*'
  skip_cleanup: true
  on:
    tags: true